name: Build and release official distrubutions
'on':
  workflow_dispatch: null
jobs:
  unschedule:
    runs-on: ubuntu-latest
    steps:
      - name: Unschedule this workflow
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.GH_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: 3f8109e185cac2c18a479c40d9b8c2fe0bc9ecfb
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/build_and_release-3f8109e185cac2c18a479c40d9b8c2fe0bc9ecfb.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
      DELAYED_JOB_PAYLOAD: '{"release":"5.3.0-rc.1","candidate":true}'
  process-payload:
    outputs:
      release: '${{ steps.parsed.outputs.release }}'
      candidate: '${{ steps.parsed.outputs.candidate }}'
    runs-on: ubuntu-latest
    steps:
      - name: Parse delayed job payload and set outputs for other jobs
        id: parsed
        run: |
          &> /dev/null command -v jq || sudo apt install jq -y

          echo "DELAYED_JOB_PAYLAOD: '$DELAYED_JOB_PAYLOAD'"

          release="$(jq -r .release <<< "$DELAYED_JOB_PEYLAOD")"
          candidate="$(jq -r .candidate <<< "$DELAYED_JOB_PAYLOAD")"
          echo "release: $release"
          echo "candidate: $candidate"

          echo "release=$release" >> $GITHUB_OUTPUT
          echo "candidate=$candidate" >> $GITHUB_OUTPUT
    env:
      DELAYED_JOB_CHECKOUT_REF: 3f8109e185cac2c18a479c40d9b8c2fe0bc9ecfb
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/build_and_release-3f8109e185cac2c18a479c40d9b8c2fe0bc9ecfb.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
      DELAYED_JOB_PAYLOAD: '{"release":"5.3.0-rc.1","candidate":true}'
  snap:
    needs:
      - process-payload
    runs-on: ubuntu-latest
    env:
      TESTS_REPO: debdutdeb/rocketchat-release-test
      DELAYED_JOB_CHECKOUT_REF: 3f8109e185cac2c18a479c40d9b8c2fe0bc9ecfb
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/build_and_release-3f8109e185cac2c18a479c40d9b8c2fe0bc9ecfb.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
      DELAYED_JOB_PAYLOAD: '{"release":"5.3.0-rc.1","candidate":true}'
    steps:
      - name: Parse environment variables
        run: |
          release="${{ needs.process-payload.outputs.release }}"
          snap_track="${release:0:1}.x"
          candidate="${{ needs.process-payload.outputs.candidate }}"

          echo "release: $release"
          echo "snap_track: $snap_track"
          echo "candidate: $candidate"

          echo "release=$release" >> $GITHUB_ENV
          echo "snap_track=$snap_track" >> $GITHUB_ENV
          echo "candidate=$candidate" >> $GITHUB_ENV
      - name: Clone release repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set build version
        working-directory: official/snap
        run: 'sed -Ei -r "/^version:/ s/ .+/ $release/" ./snap/snapcraft.yaml'
      - name: Build snap
        uses: snapcore/action-build@v1
        id: snap-build
        with:
          path: official/snap
          build-info: true
      - name: Check correct  snap path
        run: |
          snap_artifact_path="${{ steps.snap-build.outputs.snap }}"
          echo "snap_artifact_path: $snap_artifact_path"
          echo "snap_artifact_path=$snap_artifact_path" >> $GITHUB_ENV
      - name: Clone tests repo
        uses: actions/checkout@v2
        with:
          repository: '${{ env.TESTS_REPO }}'
          path: ./test_scripts
      - name: Install and test the generated snap
        run: ./test_scripts/snap_install_test.sh "$snap_artifact_path"
      - name: Remove snap
        run: sudo snap remove rocketchat-server
      - name: Test snap updating
        run: ./test_scripts/snap_update_test.sh
