name: Add submodule automatically after pr is merged

on:
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  add-submodule:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Clone submodule
        shell: bash
        run: |
          repository=$(jq '.distributions | last' unofficial.json | jq .repository -r)
          directory=${repository##*/}
          directory=${directory%.git}
          git submodule add $repository unofficial/$directory

      - name: Commit submodule
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: "commit submodule for pr ${{ fromJSON(env.GITHUB_EVENT_PATH).pull_request.number }}"
          push: true
